version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend  # Specify Dockerfile name if not default
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend  # Specify Dockerfile name if not default
    ports:
      - "8000:8000"
    volumes:
      - ./my_output:/app/output
      - ./uploaded_documents:/app/uploaded_documents
    restart: unless-stopped
