services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./my_output:/app/output
      - ./uploaded_documents:/app/uploaded_documents
    restart: unless-stopped
